name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: ["main"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [examples/CleanTag/CleanTag.ino, examples/EraseTag/EraseTag.ino, examples/FormatTag/FormatTag.ino, 
          examples/ReadTag/ReadTag.ino, examples/ReadTagExtended/ReadTagExtended.ino, examples/WriteTag/WriteTag.ino, 
          examples/WriteTagMultipleRecords/WriteTagMultipleRecords.ino]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio lib -g install "miguelbalboa/MFRC522"

      - name: Run PlatformIO
        run: |
          pio ci --lib="." --board=uno --board=nodemcuv2 --board=esp32dev --board=adafruit_feather_m4
        env:
          PLATFORMIO_BUILD_FLAGS: -DNDEF_DEBUG -DNDEF_USE_SERIAL
          PLATFORMIO_CI_SRC: ${{ matrix.example }}